# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-06 15:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Challenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', django_google_maps.fields.AddressField(max_length=200, verbose_name='Address')),
                ('geolocation', django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Geolocation')),
                ('description', models.TextField(max_length=255, null=True, verbose_name='Description')),
                ('reward_point', models.IntegerField(max_length=255, null=True, verbose_name='Reward Point')),
                ('difficulty', models.IntegerField(default=1, max_length=200, verbose_name='Difficulty')),
                ('photo', models.ImageField(null=True, upload_to='images/challenge', verbose_name='Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='Content')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Date created')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile')),
            ],
        ),
        migrations.AddField(
            model_name='acceptedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge'),
        ),
        migrations.AddField(
            model_name='acceptedchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
