# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 20:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import django_google_maps.fields


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20161203_2002'),
        ('maps', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcceptedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(max_length=255, verbose_name='Content')),
                ('date_created', models.DateField(default=django.utils.timezone.now, verbose_name='Date created')),
            ],
        ),
        migrations.CreateModel(
            name='CompletedChallenge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='challenge',
            name='description',
            field=models.TextField(max_length=255, null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(default=1, max_length=200, verbose_name='Difficulty'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(null=True, upload_to='', verbose_name='Photo'),
        ),
        migrations.AddField(
            model_name='challenge',
            name='reward_point',
            field=models.IntegerField(max_length=255, null=True, verbose_name='Reward Point'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='address',
            field=django_google_maps.fields.AddressField(max_length=200, verbose_name='Address'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='geolocation',
            field=django_google_maps.fields.GeoLocationField(max_length=100, verbose_name='Geolocation'),
        ),
        migrations.AddField(
            model_name='completedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge'),
        ),
        migrations.AddField(
            model_name='completedchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge'),
        ),
        migrations.AddField(
            model_name='acceptedchallenge',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maps.Challenge'),
        ),
        migrations.AddField(
            model_name='acceptedchallenge',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.Profile'),
        ),
    ]
