# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0002_challenge_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='price',
            field=models.IntegerField(null=True, verbose_name='Price'),
        ),
    ]
