# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_challenge_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.IntegerField(default=1, verbose_name='Difficulty'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='price',
            field=models.IntegerField(blank=True, null=True, verbose_name='Price'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='reward_point',
            field=models.IntegerField(null=True, verbose_name='Reward Point'),
        ),
    ]
