# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_auto_20161203_2021'),
        ('maps', '0003_auto_20161203_0611'),
    ]

    operations = [
    ]
