# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-07 06:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_auto_20161207_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='points',
            field=models.IntegerField(null=True, verbose_name='Points'),
        ),
    ]
