# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-03 21:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0004_merge_20161203_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='photo',
            field=models.ImageField(null=True, upload_to='images/challenge', verbose_name='Photo'),
        ),
    ]
